#!/bin/sh

# creake dir/files in /var (ramdisk)
cd /var;        mkdir tmp log empty www lock root run spool
cd /var/tmp;    touch hosts resolv.conf resolv_dnsmasq.conf resolv_3dns.conf mat
cd /var/run;    mkdir webctrl voip firmware dhcp upnpd upnpc
cd /var/spool;  ln -s /flash/cron .
cd /

# create /dev nodes on ramdisk
/bin/mount -t ramfs /dev/rd1 /dev

cd /dev
/bin/mkdir loop mtd mtdblock pts rd tts

/bin/mknod mem        c  1 1
/bin/mknod kmem       c  1 2
/bin/mknod null       c  1 3
/bin/mknod port       c  1 4
/bin/mknod zero       c  1 5
/bin/mknod full       c  1 7
/bin/mknod random     c  1 8
/bin/mknod urandom    c  1 9
/bin/mknod kmsg       c  1 11
/bin/mknod tts/0      c  4 64
/bin/mknod tts/1      c  4 65
/bin/mknod tty        c  5 0
/bin/mknod console    c  5 1
/bin/ln -s tts/0 ttyS0
/bin/mknod ptmx       c  5 2
/bin/mknod ppp        c  108 0

for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
   /bin/mknod rd/$i b 1 $i
done
for i in 0 1 2 3 4 5 6 7; do
   /bin/mknod loop/$i b 7 $i
done
for i in 0 1 2 3 4 5 6 7 8; do
   /bin/mknod mtdblock/$i b 31 $i
done
for i in 0 1 2 3; do
   /bin/mknod pts/$i c 136 $i
done

/bin/mknod mtd/0      c  90 0
/bin/mknod mtd/0ro    c  90 1
/bin/mknod mtd/1      c  90 2
/bin/mknod mtd/1ro    c  90 3
/bin/mknod mtd/2      c  90 4
/bin/mknod mtd/2ro    c  90 5
/bin/mknod mtd/3      c  90 6
/bin/mknod mtd/3ro    c  90 7
/bin/mknod mtd/4      c  90 8
/bin/mknod mtd/4ro    c  90 9
/bin/mknod mtd/5      c  90 10
/bin/mknod mtd/5ro    c  90 11
/bin/mknod mtd/6      c  90 12
/bin/mknod mtd/6ro    c  90 13
/bin/mknod mtd/7      c  90 14
/bin/mknod mtd/7ro    c  90 15
/bin/mknod mtd/8      c  90 16
/bin/mknod mtd/8ro    c  90 17

/bin/mknod sda	b 8 0
for i in 1 2 3 4 5 6 7 8; do
   /bin/mknod sda$i b 8 $i
done

/bin/mknod sdb b 8 16
for i in 1 2 3 4 5 6 7 8; do
   /bin/mknod sdb$i b 8 $(( $i + 16 ))
done

/bin/mknod sdc b 8  32
for i in 1 2 3 4 5 6 7 8; do
   /bin/mknod sdc$i b 8 $(( $i + 32 ))
done

/bin/mknod sdd b 8  48
for i in 1 2 3 4 5 6 7 8; do
   /bin/mknod sdd$i b 8 $(( $i + 48 ))
done

/bin/mknod sde b 8 64
for i in 1 2 3 4 5 6 7 8; do
   /bin/mknod sde$i b 8 $(( $i + 64 ))
done

/bin/mknod sdf b 8  80
for i in 1 2 3 4 5 6 7 8; do
   /bin/mknod sdf$i b 8 $(( $i + 80 ))
done

/bin/mknod sdg b 8 96
for i in 1 2 3 4 5 6 7 8; do
   /bin/mknod sdg$i b 8 $(( $i + 96 ))
done

/bin/mknod sdh b 8 112
for i in 1 2 3 4 5 6 7 8; do
   /bin/mknod sdh$i b 8 $(( $i + 112 ))
done



/bin/mknod sd0 b 254 0
/bin/mknod sd1 b 254 8

/bin/mknod aaci0 c 255 0
/bin/mknod aaci1 c 255 1

# linux frame buffer
/bin/mknod fb0 c 29 0

# mouse,touch panel device
mkdir input
/bin/mknod input/mouse0 c 13 32
/bin/mknod input/mouse1 c 13 33
/bin/mknod input/mice   c 13 63
/bin/mknod input/event0 c 13 64
/bin/mknod input/event1 c 13 65
cd /

